import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Layers3, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { currentUser } from '../lib/api';

export const AuthPage: React.FC = () => {
  const location = useLocation(); const navigate = useNavigate(); const { login, register } = useAuth();
  const isRegister = location.pathname === '/register';
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'TEAM_MEMBER' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { if (isRegister) await register(form); else await login(form.email, form.password); const next = new URLSearchParams(location.search).get('next'); const destination = next && next.startsWith('/') && !next.startsWith('//') ? next : currentUser()?.role === 'FACULTY' ? '/faculty/dashboard' : '/dashboard'; navigate(destination); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to connect to CapstoneHub'); } finally { setBusy(false); } };
  return <div className="min-h-screen bg-[#f7f8fc] lg:grid lg:grid-cols-[1.05fr_0.95fr]">
    <section className="hidden bg-[#16213a] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3 text-lg font-bold"><div className="rounded-xl bg-indigo-500 p-2"><Layers3 size={20}/></div>CapstoneHub</div><div className="mt-24 max-w-xl"><p className="eyebrow text-indigo-300">Academic delivery, connected</p><h1 className="mt-5 text-5xl font-semibold leading-[1.08] tracking-tight">Turn capstone work into a visible path from idea to impact.</h1><p className="mt-6 max-w-md text-lg leading-8 text-slate-300">A focused workspace for requirements, agile delivery, reviews, defects, and evidence-based progress.</p></div></div><p className="text-sm text-slate-400">Requirements → Stories → Tasks → Sprints → Deliverables</p></section>
    <section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><div className="mb-10 flex items-center gap-3 lg:hidden"><div className="rounded-xl bg-indigo-600 p-2 text-white"><Layers3 size={20}/></div><span className="font-bold text-slate-900">CapstoneHub</span></div><p className="eyebrow">{isRegister ? 'Create your workspace' : 'Welcome back'}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900">{isRegister ? 'Start a new account' : 'Sign in to your workspace'}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{isRegister ? 'Join your team and keep every delivery decision in one place.' : 'Use your CapstoneHub credentials to continue.'}</p>
      <form onSubmit={submit} className="mt-8 space-y-4">{isRegister && <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Full name</span><div className="relative"><UserRound className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-10" value={form.name} onChange={e => setForm({...form, name: e.target.value})} required placeholder="Jane Doe"/></div></label>}<label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Email</span><div className="relative"><Mail className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-10" type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})} required placeholder="you@example.com"/></div></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Password</span><div className="relative"><LockKeyhole className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-10" type="password" minLength={6} value={form.password} onChange={e => setForm({...form, password: e.target.value})} required placeholder="••••••••"/></div></label>{isRegister && <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Account type</span><select className="input" value={form.role} onChange={e => setForm({...form, role: e.target.value})}><option value="TEAM_MEMBER">Student / team member</option><option value="FACULTY">Faculty advisor</option></select></label>}{error && <div className="rounded-xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}<button className="btn-primary w-full py-3" disabled={busy}>{busy ? 'Connecting…' : isRegister ? 'Create account' : 'Sign in'}<ArrowRight size={17}/></button></form><p className="mt-8 text-center text-sm text-slate-500">{isRegister ? 'Already have an account?' : 'New to CapstoneHub?'} <Link className="font-semibold text-indigo-600 hover:text-indigo-700" to={isRegister ? '/login' : '/register'}>{isRegister ? 'Sign in' : 'Create an account'}</Link></p></div></section>
  </div>;
};
